-- Skillwright smelting chain. GENERATED by forever-data/tools/gen_skillwright_data.py - do not edit.
-- Build 1.60.1.70009, generated 2026-09-26T09:40:52+00:00.
-- Mining is not a profession Skillwright plans, but every bar in the game comes from it, and a
-- recipe that asks for bars has to be comparable with one that asks for ore.
-- [barItemID] = { howManyTheSmeltMakes, { oreID, count, ... } }
local ADDON, SW = ...
SW.Data = SW.Data or {}
SW.Data.smelting = {
    [2840] = { 1, { 2770, 1 } },  -- Smelt Copper
    [2841] = { 2, { 2840, 1, 3576, 1 } },  -- Smelt Bronze
    [2842] = { 1, { 2775, 1 } },  -- Smelt Silver
    [3575] = { 1, { 2772, 1 } },  -- Smelt Iron
    [3576] = { 1, { 2771, 1 } },  -- Smelt Tin
    [3577] = { 1, { 2776, 1 } },  -- Smelt Gold
    [3859] = { 1, { 3575, 1, 3857, 1 } },  -- Smelt Steel
    [3860] = { 1, { 3858, 1 } },  -- Smelt Mithril
    [6037] = { 1, { 7911, 1 } },  -- Smelt Truesilver
    [11371] = { 1, { 11370, 8 } },  -- Smelt Dark Iron
    [12359] = { 1, { 10620, 1 } },  -- Smelt Thorium
    [17771] = { 1, { 18562, 1, 12360, 10, 17010, 1, 18567, 3 } },  -- Smelt Elementium
    [234003] = { 1, { 12655, 2, 22203, 2 } },  -- Smelt Obsidian-Infused Thorium Bar
    [249726] = { 1, { 249426, 2, 3857, 1 } },  -- Smelt Azerothium
    [251291] = { 1, { 248815, 1 } },  -- Smelt Heavy Thorium
    [279948] = { 1, { 2838, 2, 2772, 1, 2842, 1 } },  -- Rock Garden
    [279952] = { 1, { 12359, 5, 12365, 2, 6037, 1 } },  -- Molten Foundry
    [279960] = { 1, { 2835, 1, 2840, 1 } },  -- Lodestone
}
